name: codeclusive_image_picker_example
description: Codeclusive image picker example project
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  codeclusive_image_picker:
    path: ../
  permission_handler_platform_interface: ^4.2.3
  photo_manager: ^3.5.2
  image_picker: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  permission_handler: ^11.3.1

flutter:
  uses-material-design: true
