name: codeclusive_result
description: a package for handling results in a functional way.
version: 0.0.2
homepage: codeclusive.io
issue_tracker: https://github.com/codeclusiveio/flutter-packages/issues
repository: https://github.com/codeclusiveio/flutter-packages/tree/main/codeclusive_result
documentation: https://github.com/codeclusiveio/flutter-packages/tree/main/codeclusive_result
publish_to: none

environment:
  sdk: ">=3.1.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  codeclusive_lints:
    git:
      url: https://github.com/codeclusiveio/flutter-packages.git
      path: codeclusive_lints
      ref: main
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
