name: codeclusive_lints
description: Lint rules for Dart and Flutter created and used by CodeClusive.
version: 0.0.1
homepage: https://github.com/codeclusiveio/flutter-packages/tree/codeclusive-lints/codeclusive_lints
repository: https://github.com/codeclusiveio/flutter-packages/tree/codeclusive-lints/codeclusive_lints
issue_tracker: https://github.com/codeclusiveio/flutter-packages/issues
documentation: https://github.com/codeclusiveio/flutter-packages/tree/codeclusive-lints/codeclusive_lints
publish_to: 'none'

environment:
  sdk: '>=3.0.3 <4.0.0'
