name: codeclusive_lints
description: Lint rules for Dart and Flutter created and used by CodeClusive.
version: 0.0.1
homepage: https://codeclusive.io/
repository: https://github.com/codeclusiveio/flutter-packages/tree/codeclusive-lints/codeclusive_lints
issue_tracker: https://github.com/codeclusiveio/flutter-packages/issues
documentation: https://github.com/codeclusiveio/flutter-packages/tree/codeclusive-lints/codeclusive_lints
publish_to: 'none'
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ^3.10.4

dev_dependencies:
  flutter_lints: ^3.0.0
  lints: ^3.0.0
