name: codeclusive_image_picker
description: Codeclusive package to handle picking images from devices.
version: 0.0.1
homepage: https://codeclusive.io/

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=3.13.9"

dependencies:
  device_info_plus: ^9.1.0
  flutter:
    sdk: flutter
  flutter_clean_architecture: ^5.0.4
  photo_manager: ^2.5.1+1
  permission_handler: ^10.2.0
  collection: ^1.16.0
  intl: ^0.18.0
  flutter_svg: ^2.0.7
  lottie: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
