name: codeclusive_image_picker
description: Codeclusive package to handle picking images from devices.
version: 0.0.1
homepage: https://codeclusive.io/
repository: https://github.com/codeclusiveio/flutter-packages/tree/main/codeclusive_image_picker
issue_tracker: https://github.com/codeclusiveio/flutter-packages/issues
documentation: https://github.com/codeclusiveio/flutter-packages/tree/main/codeclusive_image_picker

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=3.13.9"

dependencies:
  device_info_plus: ^9.1.0
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  photo_manager: ^2.7.1
  permission_handler: ^10.2.0
  collection: ^1.16.0
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
